package net.sourceforge.opencamera;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by Filipe Paulo on 15/01/2015.
 */
public class ColorCollection {

    public static List<Color> colors;

    public ColorCollection() {
        colors = new ArrayList<Color>();
        init();
    }

    public static String intToHex(String hex){
        String number = "#" + hex.substring(2, 8);
        return number;
    }

    public static String findColorByHex(String hex) {

        for (int i = 0; i < getColors().size(); i++) {
            Color cor = getColors().get(i);

            if(hex.compareTo(cor.getHex()) == 0 || hex.compareTo(cor.getHex()) < 0)
                return cor.getName();            


            /*
            switch (hex.compareTo(cor.getHex())) {
                case 0:
                    return cor.getHex();

                case -1:
                    if (i > 0) {
                        Color prev = colors.get(i - 1);
                        if (hex.compareTo(prev.getHex()) > 0) {
                            return prev.getHex();
                        }
                    } else {
                        return colors.get(0).getHex();
                    }
                    break;
                case 1:
                    if (i != colors.size() - 1) {
                        Color next = colors.get(i + 1);
                        if (hex.compareTo(next.getHex()) < 0) {
                            return next.getHex();
                        }
                    } else {
                        int n = colors.size() - 1;
                        return colors.get(n).getHex();
                    }
                    break;
            }
            */
        }
        return "";
    }

    public static List<Color> getColors() {
        return colors;
    }

    public static void setColors(List<Color> colors) {
        ColorCollection.colors = colors;
    }

    private void init() {

        getColors().add(new Color("#000000", "Black"));
        getColors().add(new Color("#000080", "Navy blue"));
        getColors().add(new Color("#00008b", "Dark blue"));
        getColors().add(new Color("#00009c", "Duke blue"));
        getColors().add(new Color("#0000cd", "Medium blue"));
        getColors().add(new Color("#0000ff", "Blue"));
        getColors().add(new Color("#000f89", "Phthalo blue"));
        getColors().add(new Color("#0014a8", "Zaffre"));
        getColors().add(new Color("#002147", "Oxford Blue"));
        getColors().add(new Color("#002e63", "Cool black"));
        getColors().add(new Color("#002fa7", "International Klein Blue"));
        getColors().add(new Color("#003153", "Prussian blue"));
        getColors().add(new Color("#003366", "Dark midnight blue"));
        getColors().add(new Color("#003399", "Dark powder blue"));
        getColors().add(new Color("#003399", "Smalt"));
        getColors().add(new Color("#0033aa", "UA blue"));
        getColors().add(new Color("#0038a8", "Royal azure"));
        getColors().add(new Color("#004040", "Rich black"));
        getColors().add(new Color("#004225", "British racing green"));
        getColors().add(new Color("#004242", "Warm black"));
        getColors().add(new Color("#0047ab", "Cobalt"));
        getColors().add(new Color("#004953", "Midnight green"));
        getColors().add(new Color("#004b49", "Deep jungle green"));
        getColors().add(new Color("#0054b4", "Medium teal blue"));
        getColors().add(new Color("#00563f", "Sacramento State green"));
        getColors().add(new Color("#006600", "Pakistan green"));
        getColors().add(new Color("#0067a5", "Medium Persian blue"));
        getColors().add(new Color("#00693e", "Dartmouth green"));
        getColors().add(new Color("#006994", "Sea blue"));
        getColors().add(new Color("#006a4e", "Bottle green"));
        getColors().add(new Color("#006b3c", "Cadmium green"));
        getColors().add(new Color("#006d5b", "Teal green"));
        getColors().add(new Color("#0070ff", "Brandeis blue"));
        getColors().add(new Color("#0072bb", "French blue"));
        getColors().add(new Color("#0073cf", "True Blue"));
        getColors().add(new Color("#007474", "Skobeloff"));
        getColors().add(new Color("#00755e", "Tropical rain forest"));
        getColors().add(new Color("#0077be", "Ocean Boat Blue"));
        getColors().add(new Color("#007aa5", "CG Blue"));
        getColors().add(new Color("#007ba7", "Cerulean"));
        getColors().add(new Color("#007fff", "Azure"));
        getColors().add(new Color("#008000", "Ao"));
        getColors().add(new Color("#008000", "Office green"));
        getColors().add(new Color("#008080", "Stormcloud"));
        getColors().add(new Color("#008080", "Teal"));
        getColors().add(new Color("#008b8b", "Dark cyan"));
        getColors().add(new Color("#009000", "Islamic green"));
        getColors().add(new Color("#0095b6", "Bondi blue"));
        getColors().add(new Color("#009e60", "Shamrock green"));
        getColors().add(new Color("#00a86b", "Jade"));
        getColors().add(new Color("#00bfff", "Capri"));
        getColors().add(new Color("#00bfff", "Deep sky blue"));
        getColors().add(new Color("#00cc99", "Caribbean green"));
        getColors().add(new Color("#00ced1", "Dark turquoise"));
        getColors().add(new Color("#00fa9a", "Medium spring green"));
        getColors().add(new Color("#00ff00", "Electric green"));
        getColors().add(new Color("#00ff00", "Green"));
        getColors().add(new Color("#00ff7f", "Guppie green"));
        getColors().add(new Color("#00ff7f", "Spring green"));
        getColors().add(new Color("#00ffef", "Turquoise blue"));
        getColors().add(new Color("#00ffff", "Aqua"));
        getColors().add(new Color("#00ffff", "Cyan"));
        getColors().add(new Color("#00ffff", "Electric cyan"));
        getColors().add(new Color("#00ffff", "Waterspout"));
        getColors().add(new Color("#013220", "Dark green"));
        getColors().add(new Color("#014421", "UP Forest green"));
        getColors().add(new Color("#01796f", "Pine green"));
        getColors().add(new Color("#035096", "Medium electric blue"));
        getColors().add(new Color("#03c03c", "Dark pastel green"));
        getColors().add(new Color("#059033", "North Texas Green"));
        getColors().add(new Color("#08457e", "Dark cerulean"));
        getColors().add(new Color("#087830", "La Salle Green"));
        getColors().add(new Color("#0892d0", "Rich electric blue"));
        getColors().add(new Color("#08e8de", "Bright turquoise"));
        getColors().add(new Color("#0abab5", "Tiffany Blue"));
        getColors().add(new Color("#0bda51", "Malachite"));
        getColors().add(new Color("#0d98ba", "Blue green"));
        getColors().add(new Color("#0f0f0f", "Onyx"));
        getColors().add(new Color("#0f4d92", "Yale Blue"));
        getColors().add(new Color("#0f52ba", "Sapphire"));
        getColors().add(new Color("#0fc0fc", "Spiro Disco Ball"));
        getColors().add(new Color("#100c08", "Smoky black"));
        getColors().add(new Color("#1034a6", "Egyptian blue"));
        getColors().add(new Color("#1164b4", "Green Blue"));
        getColors().add(new Color("#120a8f", "Ultramarine"));
        getColors().add(new Color("#123524", "Phthalo green"));
        getColors().add(new Color("#138808", "India green"));
        getColors().add(new Color("#1560bd", "Denim"));
        getColors().add(new Color("#177245", "Dark spring green"));
        getColors().add(new Color("#18453b", "MSU Green"));
        getColors().add(new Color("#191970", "Midnight blue"));
        getColors().add(new Color("#195905", "Lincoln green"));
        getColors().add(new Color("#1a2421", "Dark jungle green"));
        getColors().add(new Color("#1c352d", "Medium jungle green"));
        getColors().add(new Color("#1c39bb", "Persian blue"));
        getColors().add(new Color("#1ca9c9", "Pacific Blue"));
        getColors().add(new Color("#1dacd6", "Bright cerulean"));
        getColors().add(new Color("#1e4d2b", "Cal Poly Pomona green"));
        getColors().add(new Color("#1e90ff", "Dodger blue"));
        getColors().add(new Color("#1fcecb", "Robin&#039;s Egg Blue"));
        getColors().add(new Color("#20b2aa", "Light sea green"));
        getColors().add(new Color("#21421e", "Myrtle"));
        getColors().add(new Color("#21abcd", "Ball Blue"));
        getColors().add(new Color("#228b22", "Forest green"));
        getColors().add(new Color("#23297a", "Saint Patrick Blue"));
        getColors().add(new Color("#26619c", "Lapis lazuli"));
        getColors().add(new Color("#273be2", "Palatinate blue"));
        getColors().add(new Color("#29ab87", "Jungle green"));
        getColors().add(new Color("#2a52be", "Cerulean blue"));
        getColors().add(new Color("#2a8000", "Napier green"));
        getColors().add(new Color("#2c1608", "Zinnwaldite brown"));
        getColors().add(new Color("#2e8b57", "Sea green"));
        getColors().add(new Color("#2f4f4f", "Dark slate gray"));
        getColors().add(new Color("#30ba8f", "Mountain Meadow"));
        getColors().add(new Color("#30d5c8", "Turquoise"));
        getColors().add(new Color("#318ce7", "Bleu de France"));
        getColors().add(new Color("#32127a", "Persian indigo"));
        getColors().add(new Color("#321414", "Seal brown"));
        getColors().add(new Color("#324ab2", "Violet Blue"));
        getColors().add(new Color("#32cd32", "Lime green"));
        getColors().add(new Color("#355e3b", "Hunter green"));
        getColors().add(new Color("#36454f", "Charcoal"));
        getColors().add(new Color("#367588", "Teal blue"));
        getColors().add(new Color("#39ff14", "Neon green"));
        getColors().add(new Color("#3c1414", "Dark sienna"));
        getColors().add(new Color("#3cb371", "Medium sea green"));
        getColors().add(new Color("#3cd070", "UFO Green"));
        getColors().add(new Color("#3d2b1f", "Bistre"));
        getColors().add(new Color("#3eb489", "Mint"));
        getColors().add(new Color("#3f00ff", "Electric ultramarine"));
        getColors().add(new Color("#3fff00", "Harlequin"));
        getColors().add(new Color("#40826d", "Viridian"));
        getColors().add(new Color("#414833", "Rifle green"));
        getColors().add(new Color("#414a4c", "Outer Space"));
        getColors().add(new Color("#4166f5", "Ultramarine blue"));
        getColors().add(new Color("#4169e1", "Royal blue"));
        getColors().add(new Color("#417dc1", "Tufts Blue"));
        getColors().add(new Color("#43b3ae", "Verdigris"));
        getColors().add(new Color("#446ccf", "Han blue"));
        getColors().add(new Color("#45cea2", "Shamrock"));
        getColors().add(new Color("#465945", "Gray asparagus"));
        getColors().add(new Color("#4682b4", "Steel blue"));
        getColors().add(new Color("#480607", "Bulgarian rose"));
        getColors().add(new Color("#483c32", "Dark lava"));
        getColors().add(new Color("#483c32", "Dark taupe"));
        getColors().add(new Color("#483c32", "Taupe"));
        getColors().add(new Color("#483d8b", "Dark slate blue"));
        getColors().add(new Color("#48d1cc", "Medium turquoise"));
        getColors().add(new Color("#49796b", "Hooker green"));
        getColors().add(new Color("#4997d0", "Celestial blue"));
        getColors().add(new Color("#4b0082", "Indigo"));
        getColors().add(new Color("#4b3621", "Café noir"));
        getColors().add(new Color("#4b5320", "Army green"));
        getColors().add(new Color("#4cbb17", "Kelly green"));
        getColors().add(new Color("#4d5d53", "Feldgrau"));
        getColors().add(new Color("#4f7942", "Fern green"));
        getColors().add(new Color("#50404d", "Purple taupe"));
        getColors().add(new Color("#507d2a", "Sap green"));
        getColors().add(new Color("#50c878", "Emerald"));
        getColors().add(new Color("#50c878", "Paris Green"));
        getColors().add(new Color("#5218fa", "Han purple"));
        getColors().add(new Color("#534b4f", "Liver"));
        getColors().add(new Color("#536872", "Cadet"));
        getColors().add(new Color("#536878", "Dark electric blue"));
        getColors().add(new Color("#536878", "Payne grey"));
        getColors().add(new Color("#536895", "UCLA Blue"));
        getColors().add(new Color("#555555", "Davy grey"));
        getColors().add(new Color("#556b2f", "Dark olive green"));
        getColors().add(new Color("#560319", "Dark scarlet"));
        getColors().add(new Color("#592720", "Caput mortuum"));
        getColors().add(new Color("#5a4fcf", "Iris"));
        getColors().add(new Color("#5b92e5", "United Nations blue"));
        getColors().add(new Color("#5d3954", "Dark byzantium"));
        getColors().add(new Color("#5d8aa8", "Air Force blue"));
        getColors().add(new Color("#5d8aa8", "Rackley"));
        getColors().add(new Color("#5f9ea0", "Cadet blue"));
        getColors().add(new Color("#6050dc", "Majorelle Blue"));
        getColors().add(new Color("#6082b6", "Glaucous"));
        getColors().add(new Color("#614051", "Eggplant"));
        getColors().add(new Color("#635147", "Umber"));
        getColors().add(new Color("#645452", "Wenge"));
        getColors().add(new Color("#6495ed", "Cornflower blue"));
        getColors().add(new Color("#65000b", "Rosewood"));
        getColors().add(new Color("#654321", "Dark brown"));
        getColors().add(new Color("#654321", "Otter brown"));
        getColors().add(new Color("#66023c", "Tyrian purple"));
        getColors().add(new Color("#663854", "Halayà úbe"));
        getColors().add(new Color("#66424d", "Tuscan red"));
        getColors().add(new Color("#6699cc", "Blue Gray"));
        getColors().add(new Color("#66ddaa", "Medium aquamarine"));
        getColors().add(new Color("#66ff00", "Bright green"));
        getColors().add(new Color("#673147", "Old mauve"));
        getColors().add(new Color("#674846", "Rose ebony"));
        getColors().add(new Color("#674c47", "Medium taupe"));
        getColors().add(new Color("#682860", "Palatinate purple"));
        getColors().add(new Color("#69359c", "Purple Heart"));
        getColors().add(new Color("#696969", "Dim gray"));
        getColors().add(new Color("#6a5acd", "Slate blue"));
        getColors().add(new Color("#6b8e23", "Olive Drab"));
        getColors().add(new Color("#6c541e", "Field drab"));
        getColors().add(new Color("#6e7f80", "AuroMetalSaurus"));
        getColors().add(new Color("#6f00ff", "Electric indigo"));
        getColors().add(new Color("#6f4e37", "Coffee"));
        getColors().add(new Color("#701c1c", "Persian plum"));
        getColors().add(new Color("#702963", "Byzantium"));
        getColors().add(new Color("#704214", "Sepia"));
        getColors().add(new Color("#704241", "Deep coffee"));
        getColors().add(new Color("#708090", "Slate gray"));
        getColors().add(new Color("#71bc78", "Fern"));
        getColors().add(new Color("#722f37", "Wine"));
        getColors().add(new Color("#734f96", "Dark lavender"));
        getColors().add(new Color("#738678", "Xanadu"));
        getColors().add(new Color("#73a9c2", "Moonstone blue"));
        getColors().add(new Color("#73c2fb", "Maya blue"));
        getColors().add(new Color("#746cc0", "Toolbox"));
        getColors().add(new Color("#74c365", "Mantis"));
        getColors().add(new Color("#76ff7a", "Screamin Green"));
        getColors().add(new Color("#778899", "Light slate gray"));
        getColors().add(new Color("#779ecb", "Dark pastel blue"));
        getColors().add(new Color("#77dd77", "Pastel green"));
        getColors().add(new Color("#78184a", "Pansy purple"));
        getColors().add(new Color("#7851a9", "Royal purple"));
        getColors().add(new Color("#78866b", "Camouflage green"));
        getColors().add(new Color("#79443b", "Bole"));
        getColors().add(new Color("#796878", "Old lavender"));
        getColors().add(new Color("#7b1113", "UP Maroon"));
        getColors().add(new Color("#7b68ee", "Medium slate blue"));
        getColors().add(new Color("#7cfc00", "Lawn green"));
        getColors().add(new Color("#7df9ff", "Electric blue"));
        getColors().add(new Color("#7fff00", "Chartreuse"));
        getColors().add(new Color("#7fffd4", "Aquamarine"));
        getColors().add(new Color("#800000", "Maroon"));
        getColors().add(new Color("#800020", "Burgundy"));
        getColors().add(new Color("#800080", "Patriarch"));
        getColors().add(new Color("#800080", "Purple"));
        getColors().add(new Color("#801818", "Falu red"));
        getColors().add(new Color("#80461b", "Russet"));
        getColors().add(new Color("#808000", "Heart Gold"));
        getColors().add(new Color("#808000", "Olive"));
        getColors().add(new Color("#808080", "Gray"));
        getColors().add(new Color("#808080", "Trolley Grey"));
        getColors().add(new Color("#836953", "Pastel brown"));
        getColors().add(new Color("#848482", "Battleship grey"));
        getColors().add(new Color("#85bb65", "Dollar bill"));
        getColors().add(new Color("#86608e", "French lilac"));
        getColors().add(new Color("#872657", "Dark raspberry"));
        getColors().add(new Color("#873260", "Boysenberry"));
        getColors().add(new Color("#87a96b", "Asparagus"));
        getColors().add(new Color("#87ceeb", "Sky blue"));
        getColors().add(new Color("#87cefa", "Light sky blue"));
        getColors().add(new Color("#882d17", "Sienna"));
        getColors().add(new Color("#8878c3", "Ube"));
        getColors().add(new Color("#88d8c0", "Pearl Aqua"));
        getColors().add(new Color("#893f45", "Cordovan"));
        getColors().add(new Color("#89cff0", "Baby blue"));
        getColors().add(new Color("#8a2be2", "Blue purple"));
        getColors().add(new Color("#8a2be2", "Blue violet"));
        getColors().add(new Color("#8a3324", "Burnt umber"));
        getColors().add(new Color("#8a496b", "Twilight lavender"));
        getColors().add(new Color("#8a795d", "Shadow"));
        getColors().add(new Color("#8b0000", "Dark red"));
        getColors().add(new Color("#8b008b", "Dark magenta"));
        getColors().add(new Color("#8b4513", "Saddle brown"));
        getColors().add(new Color("#8b8589", "Taupe gray"));
        getColors().add(new Color("#8c92ac", "Cool grey"));
        getColors().add(new Color("#8db600", "Apple green"));
        getColors().add(new Color("#8f00ff", "Electric violet"));
        getColors().add(new Color("#8fbc8f", "Dark sea green"));
        getColors().add(new Color("#905d5d", "Rose taupe"));
        getColors().add(new Color("#90ee90", "Light green"));
        getColors().add(new Color("#915c83", "Antique fuchsia"));
        getColors().add(new Color("#915f6d", "Mauve taupe"));
        getColors().add(new Color("#915f6d", "Raspberry glace"));
        getColors().add(new Color("#918151", "Dark tan"));
        getColors().add(new Color("#91a3b0", "Cadet grey"));
        getColors().add(new Color("#922724", "Vivid auburn"));
        getColors().add(new Color("#933d41", "Smokey topaz"));
        getColors().add(new Color("#9370db", "Medium purple"));
        getColors().add(new Color("#93c572", "Pistachio"));
        getColors().add(new Color("#93ccea", "Light cornflower blue"));
        getColors().add(new Color("#9400d3", "Dark violet"));
        getColors().add(new Color("#9457eb", "Lavender indigo"));
        getColors().add(new Color("#966fd6", "Dark pastel purple"));
        getColors().add(new Color("#967117", "Drab"));
        getColors().add(new Color("#967117", "Mode beige"));
        getColors().add(new Color("#967117", "Sand dune"));
        getColors().add(new Color("#967117", "Sandy taupe"));
        getColors().add(new Color("#9678b6", "Purple mountain majesty"));
        getColors().add(new Color("#967bb6", "Lavender purple"));
        getColors().add(new Color("#96c8a2", "Eton blue"));
        getColors().add(new Color("#96ded1", "Pale robin egg blue"));
        getColors().add(new Color("#979aaa", "Manatee"));
        getColors().add(new Color("#986960", "Dark chestnut"));
        getColors().add(new Color("#987654", "Pale brown"));
        getColors().add(new Color("#98777b", "Bazaar"));
        getColors().add(new Color("#98817b", "Cinereous"));
        getColors().add(new Color("#98fb98", "Pale green"));
        getColors().add(new Color("#98ff98", "Mint green"));
        getColors().add(new Color("#990000", "Crimson Red"));
        getColors().add(new Color("#990000", "Stizza"));
        getColors().add(new Color("#990000", "USC Cardinal"));
        getColors().add(new Color("#9932cc", "Dark orchid"));
        getColors().add(new Color("#9955bb", "Deep lilac"));
        getColors().add(new Color("#996515", "Golden brown"));
        getColors().add(new Color("#996666", "Copper rose"));
        getColors().add(new Color("#9966cc", "Amethyst"));
        getColors().add(new Color("#997a8d", "Mountbatten pink"));
        getColors().add(new Color("#99badd", "Carolina blue"));
        getColors().add(new Color("#9ab973", "Olivine"));
        getColors().add(new Color("#9acd32", "Yellow green"));
        getColors().add(new Color("#9aceeb", "Cornflower"));
        getColors().add(new Color("#9bc4e2", "Pale cerulean"));
        getColors().add(new Color("#9bddff", "Columbia blue"));
        getColors().add(new Color("#9d81ba", "Purple Mountain&#039;s Majesty"));
        getColors().add(new Color("#9f00ff", "Vivid violet"));
        getColors().add(new Color("#9f1d35", "Vivid burgundy"));
        getColors().add(new Color("#9f8170", "Beaver"));
        getColors().add(new Color("#a020f0", "Veronica"));
        getColors().add(new Color("#a0785a", "Chamoisee"));
        getColors().add(new Color("#a0d6b4", "Turquoise green"));
        getColors().add(new Color("#a1caf1", "Baby blue eyes"));
        getColors().add(new Color("#a2a2d0", "Blue Bell"));
        getColors().add(new Color("#a2add0", "Wild blue yonder"));
        getColors().add(new Color("#a3c1ad", "Cambridge Blue"));
        getColors().add(new Color("#a40000", "Dark candy apple red"));
        getColors().add(new Color("#a4c639", "Android Green"));
        getColors().add(new Color("#a4dded", "Non photo blue"));
        getColors().add(new Color("#a50b5e", "Jazzberry jam"));
        getColors().add(new Color("#a52a2a", "Auburn"));
        getColors().add(new Color("#a52a2a", "Brown"));
        getColors().add(new Color("#a52a2a", "Red brown"));
        getColors().add(new Color("#a67b5b", "Café au lait"));
        getColors().add(new Color("#a67b5b", "French beige"));
        getColors().add(new Color("#a7fc00", "Spring bud"));
        getColors().add(new Color("#a81c07", "Rufous"));
        getColors().add(new Color("#a8e4a0", "Granny Smith Apple"));
        getColors().add(new Color("#a9203e", "Deep carmine"));
        getColors().add(new Color("#a99a86", "Grullo"));
        getColors().add(new Color("#a9a9a9", "Dark gray"));
        getColors().add(new Color("#a9ba9d", "Laurel green"));
        getColors().add(new Color("#aa98a9", "Rose quartz"));
        getColors().add(new Color("#aaf0d1", "Magic mint"));
        getColors().add(new Color("#ab4e52", "Rose vale"));
        getColors().add(new Color("#abcdef", "Pale cornflower blue"));
        getColors().add(new Color("#ace1af", "Celadon"));
        getColors().add(new Color("#ace5ee", "Blizzard Blue"));
        getColors().add(new Color("#add8e6", "Light blue"));
        getColors().add(new Color("#addfad", "Moss green"));
        getColors().add(new Color("#adff2f", "Green yellow"));
        getColors().add(new Color("#ae0c00", "Mordant red 19"));
        getColors().add(new Color("#ae2029", "Upsdell red"));
        getColors().add(new Color("#aec6cf", "Pastel blue"));
        getColors().add(new Color("#af4035", "Medium carmine"));
        getColors().add(new Color("#af4035", "Pale carmine"));
        getColors().add(new Color("#afeeee", "Pale blue"));
        getColors().add(new Color("#b03060", "Rich maroon"));
        getColors().add(new Color("#b06500", "Ginger"));
        getColors().add(new Color("#b0e0e6", "Powder blue"));
        getColors().add(new Color("#b19cd9", "Light pastel purple"));
        getColors().add(new Color("#b22222", "Firebrick"));
        getColors().add(new Color("#b2beb5", "Ash grey"));
        getColors().add(new Color("#b2ec5d", "Inchworm"));
        getColors().add(new Color("#b2ffff", "Celeste"));
        getColors().add(new Color("#b31b1b", "Carnelian"));
        getColors().add(new Color("#b31b1b", "Cornell Red"));
        getColors().add(new Color("#b3446c", "Raspberry rose"));
        getColors().add(new Color("#b38b6d", "Light taupe"));
        getColors().add(new Color("#b39eb5", "Pastel purple"));
        getColors().add(new Color("#b53389", "Fandango"));
        getColors().add(new Color("#b5651d", "Light brown"));
        getColors().add(new Color("#b57281", "Turkish rose"));
        getColors().add(new Color("#b5a642", "Brass"));
        getColors().add(new Color("#b666d2", "Rich lilac"));
        getColors().add(new Color("#b7410e", "Rust"));
        getColors().add(new Color("#b76e79", "Rose gold"));
        getColors().add(new Color("#b784a7", "Opera mauve"));
        getColors().add(new Color("#b78727", "University of California Gold"));
        getColors().add(new Color("#b87333", "Copper"));
        getColors().add(new Color("#b8860b", "Dark goldenrod"));
        getColors().add(new Color("#b94e48", "Deep chestnut"));
        getColors().add(new Color("#ba55d3", "Medium orchid"));
        getColors().add(new Color("#bab86c", "Olive Green"));
        getColors().add(new Color("#bb3385", "Medium red violet"));
        getColors().add(new Color("#bb6528", "Ruddy brown"));
        getColors().add(new Color("#bc8f8f", "Rosy brown"));
        getColors().add(new Color("#bc987e", "Pale taupe"));
        getColors().add(new Color("#bcd4e6", "Beau blue"));
        getColors().add(new Color("#bcd4e6", "Pale aqua"));
        getColors().add(new Color("#bd33a4", "Byzantine"));
        getColors().add(new Color("#bdb76b", "Dark khaki"));
        getColors().add(new Color("#bdda57", "June bud"));
        getColors().add(new Color("#be0032", "Crimson glory"));
        getColors().add(new Color("#bf00ff", "Electric purple"));
        getColors().add(new Color("#bf94e4", "Bright lavender"));
        getColors().add(new Color("#bfff00", "Lemon lime"));
        getColors().add(new Color("#bfff00", "Lime"));
        getColors().add(new Color("#c04000", "Mahogany"));
        getColors().add(new Color("#c08081", "Old rose"));
        getColors().add(new Color("#c0c0c0", "Silver"));
        getColors().add(new Color("#c154c1", "Deep fuchsia"));
        getColors().add(new Color("#c19a6b", "Camel"));
        getColors().add(new Color("#c19a6b", "Desert"));
        getColors().add(new Color("#c19a6b", "Fallow"));
        getColors().add(new Color("#c19a6b", "Lion"));
        getColors().add(new Color("#c23b22", "Dark pastel red"));
        getColors().add(new Color("#c2b280", "Ecru"));
        getColors().add(new Color("#c2b280", "Sand"));
        getColors().add(new Color("#c32148", "Bright maroon"));
        getColors().add(new Color("#c3b091", "Khaki"));
        getColors().add(new Color("#c41e3a", "Cardinal"));
        getColors().add(new Color("#c4c3d0", "Lavender gray"));
        getColors().add(new Color("#c54b8c", "Mulberry"));
        getColors().add(new Color("#c5b358", "Vegas gold"));
        getColors().add(new Color("#c71585", "Medium violet red"));
        getColors().add(new Color("#c71585", "Red violet"));
        getColors().add(new Color("#c80815", "Venetian red"));
        getColors().add(new Color("#c8a2c8", "Lilac"));
        getColors().add(new Color("#c90016", "Harvard crimson"));
        getColors().add(new Color("#c9a0dc", "Wisteria"));
        getColors().add(new Color("#c9c0bb", "Pale silver"));
        getColors().add(new Color("#c9dc87", "Medium spring bud"));
        getColors().add(new Color("#ca2c92", "Royal fuchsia"));
        getColors().add(new Color("#cb410b", "Sinopia"));
        getColors().add(new Color("#cb4154", "Brick red"));
        getColors().add(new Color("#cb99c9", "Pastel violet"));
        getColors().add(new Color("#cba135", "Satin sheen gold"));
        getColors().add(new Color("#cc0000", "Boston University Red"));
        getColors().add(new Color("#cc00cc", "Deep magenta"));
        getColors().add(new Color("#cc3333", "Persian red"));
        getColors().add(new Color("#cc4e5c", "Dark terra cotta"));
        getColors().add(new Color("#cc5500", "Burnt orange"));
        getColors().add(new Color("#cc6666", "Fuzzy Wuzzy"));
        getColors().add(new Color("#cc7722", "Ochre"));
        getColors().add(new Color("#cc8899", "Puce"));
        getColors().add(new Color("#ccccff", "Lavender blue"));
        getColors().add(new Color("#ccccff", "Periwinkle"));
        getColors().add(new Color("#ccff00", "Electric lime"));
        getColors().add(new Color("#ccff00", "Fluorescent yellow"));
        getColors().add(new Color("#cd5700", "Tawny"));
        getColors().add(new Color("#cd5b45", "Dark coral"));
        getColors().add(new Color("#cd5c5c", "Chestnut"));
        getColors().add(new Color("#cd5c5c", "Indian red"));
        getColors().add(new Color("#cd7f32", "Bronze"));
        getColors().add(new Color("#cd9575", "Antique brass"));
        getColors().add(new Color("#ce2029", "Fire engine red"));
        getColors().add(new Color("#cf1020", "Lava"));
        getColors().add(new Color("#cf71af", "Sky magenta"));
        getColors().add(new Color("#cfb53b", "Old gold"));
        getColors().add(new Color("#cfcfc4", "Pastel gray"));
        getColors().add(new Color("#d0f0c0", "Tea green"));
        getColors().add(new Color("#d19fe8", "Bright ube"));
        getColors().add(new Color("#d1e231", "Pear"));
        getColors().add(new Color("#d2691e", "Chocolate"));
        getColors().add(new Color("#d2691e", "Cinnamon"));
        getColors().add(new Color("#d2691e", "Cocoa brown"));
        getColors().add(new Color("#d2b48c", "Tan"));
        getColors().add(new Color("#d3003f", "Utah Crimson"));
        getColors().add(new Color("#d3d3d3", "Light gray"));
        getColors().add(new Color("#d40000", "Rosso corsa"));
        getColors().add(new Color("#d68a59", "Raw Sienna"));
        getColors().add(new Color("#d6cadd", "Languid lavender"));
        getColors().add(new Color("#d70040", "Rich carmine"));
        getColors().add(new Color("#d70a53", "Debian red"));
        getColors().add(new Color("#d71868", "Dogwood rose"));
        getColors().add(new Color("#d73b3e", "Jasper"));
        getColors().add(new Color("#d8bfd8", "Thistle"));
        getColors().add(new Color("#d9004c", "UA red"));
        getColors().add(new Color("#d99058", "Persian orange"));
        getColors().add(new Color("#da1d81", "Vivid cerise"));
        getColors().add(new Color("#da3287", "Deep cerise"));
        getColors().add(new Color("#da70d6", "Orchid"));
        getColors().add(new Color("#da8a67", "Pale copper"));
        getColors().add(new Color("#da9100", "Harvest Gold"));
        getColors().add(new Color("#daa520", "Goldenrod"));
        getColors().add(new Color("#db7093", "Pale red violet"));
        getColors().add(new Color("#db7093", "Pale violet red"));
        getColors().add(new Color("#dbd7d2", "Timberwolf"));
        getColors().add(new Color("#dc143c", "Crimson"));
        getColors().add(new Color("#dcd0ff", "Pale lavender"));
        getColors().add(new Color("#dcdcdc", "Gainsboro"));
        getColors().add(new Color("#dda0dd", "Medium lavender magenta"));
        getColors().add(new Color("#dda0dd", "Pale plum"));
        getColors().add(new Color("#dda0dd", "Plum"));
        getColors().add(new Color("#ddadaf", "Pale chestnut"));
        getColors().add(new Color("#de3163", "Cerise"));
        getColors().add(new Color("#de3163", "Cherry"));
        getColors().add(new Color("#de5d83", "Blush"));
        getColors().add(new Color("#de6fa1", "Thulian pink"));
        getColors().add(new Color("#deaa88", "Tumbleweed"));
        getColors().add(new Color("#deb887", "Burlywood"));
        getColors().add(new Color("#df00ff", "Phlox"));
        getColors().add(new Color("#df00ff", "Psychedelic purple"));
        getColors().add(new Color("#df73ff", "Heliotrope"));
        getColors().add(new Color("#e0115f", "Ruby"));
        getColors().add(new Color("#e03c31", "CG Red"));
        getColors().add(new Color("#e08d3c", "Tiger eye"));
        getColors().add(new Color("#e0b0ff", "Mauve"));
        getColors().add(new Color("#e0ffff", "Light cyan"));
        getColors().add(new Color("#e18e96", "Ruddy pink"));
        getColors().add(new Color("#e1a95f", "Earth yellow"));
        getColors().add(new Color("#e1ad21", "Urobilin"));
        getColors().add(new Color("#e2062c", "Medium candy apple red"));
        getColors().add(new Color("#e25098", "Raspberry pink"));
        getColors().add(new Color("#e25822", "Flame"));
        getColors().add(new Color("#e2725b", "Terra cotta"));
        getColors().add(new Color("#e30022", "Cadmium red"));
        getColors().add(new Color("#e30b5d", "Raspberry"));
        getColors().add(new Color("#e3256b", "Razzmatazz"));
        getColors().add(new Color("#e32636", "Alizarin crimson"));
        getColors().add(new Color("#e32636", "Rose madder"));
        getColors().add(new Color("#e34234", "Cinnabar"));
        getColors().add(new Color("#e34234", "Vermilion"));
        getColors().add(new Color("#e3a857", "Indian yellow"));
        getColors().add(new Color("#e3dac9", "Bone"));
        getColors().add(new Color("#e4717a", "Candy pink"));
        getColors().add(new Color("#e48400", "Fulvous"));
        getColors().add(new Color("#e49b0f", "Gamboge"));
        getColors().add(new Color("#e4d00a", "Citrine"));
        getColors().add(new Color("#e4d96f", "Straw"));
        getColors().add(new Color("#e52b50", "Amaranth"));
        getColors().add(new Color("#e5aa70", "Fawn"));
        getColors().add(new Color("#e5b73b", "Meat brown"));
        getColors().add(new Color("#e5e4e2", "Platinum"));
        getColors().add(new Color("#e62020", "Lust"));
        getColors().add(new Color("#e66771", "Light carmine pink"));
        getColors().add(new Color("#e68fac", "Light Thulian pink"));
        getColors().add(new Color("#e6be8a", "Pale gold"));
        getColors().add(new Color("#e6e200", "Peridot"));
        getColors().add(new Color("#e6e6fa", "Lavender mist"));
        getColors().add(new Color("#e6e6fa", "Lavender"));
        getColors().add(new Color("#e6e8fa", "Glitter"));
        getColors().add(new Color("#e75480", "Dark pink"));
        getColors().add(new Color("#e7accf", "Pink pearl"));
        getColors().add(new Color("#e7feff", "Bubbles"));
        getColors().add(new Color("#e8000d", "KU Crimson"));
        getColors().add(new Color("#e9692c", "Deep carrot orange"));
        getColors().add(new Color("#e97451", "Burnt sienna"));
        getColors().add(new Color("#e9967a", "Dark salmon"));
        getColors().add(new Color("#e9d66b", "Arylide yellow"));
        getColors().add(new Color("#e9d66b", "Hansa yellow"));
        getColors().add(new Color("#eae0c8", "Pearl"));
        getColors().add(new Color("#eb4c42", "Carmine pink"));
        getColors().add(new Color("#ec3b83", "Cerise pink"));
        getColors().add(new Color("#ecd540", "Sandstorm"));
        getColors().add(new Color("#ecebbd", "Pale spring bud"));
        getColors().add(new Color("#ed872d", "Cadmium orange"));
        getColors().add(new Color("#ed9121", "Carrot orange"));
        getColors().add(new Color("#edc9af", "Desert sand"));
        getColors().add(new Color("#ee82ee", "Lavender magenta"));
        getColors().add(new Color("#ee82ee", "Violet"));
        getColors().add(new Color("#eedc82", "Flax"));
        getColors().add(new Color("#eee600", "Titanium yellow"));
        getColors().add(new Color("#eee8aa", "Pale goldenrod"));
        getColors().add(new Color("#ef3038", "Deep carmine pink"));
        getColors().add(new Color("#ef98aa", "Mauvelous"));
        getColors().add(new Color("#efdecd", "Almond"));
        getColors().add(new Color("#f08080", "Light coral"));
        getColors().add(new Color("#f0dc82", "Buff"));
        getColors().add(new Color("#f0e130", "Dandelion"));
        getColors().add(new Color("#f0e68c", "Light khaki"));
        getColors().add(new Color("#f0ead6", "Eggshell"));
        getColors().add(new Color("#f0f8ff", "Alice blue"));
        getColors().add(new Color("#f0fff0", "Honeydew"));
        getColors().add(new Color("#f0ffff", "Azure mist/web"));
        getColors().add(new Color("#f28500", "Tangerine"));
        getColors().add(new Color("#f2f3f4", "Anti flash white"));
        getColors().add(new Color("#f2f3f4", "Munsell"));
        getColors().add(new Color("#f3e5ab", "Medium champagne"));
        getColors().add(new Color("#f3e5ab", "Vanilla"));
        getColors().add(new Color("#f400a1", "Fashion fuchsia"));
        getColors().add(new Color("#f400a1", "Hollywood cerise"));
        getColors().add(new Color("#f49ac2", "Pastel magenta"));
        getColors().add(new Color("#f4a460", "Sandy brown"));
        getColors().add(new Color("#f4bbff", "Brilliant lavender"));
        getColors().add(new Color("#f4bbff", "Electric lavender"));
        getColors().add(new Color("#f4c2c2", "Baby pink"));
        getColors().add(new Color("#f4c2c2", "Tea rose"));
        getColors().add(new Color("#f4c430", "Saffron"));
        getColors().add(new Color("#f4f0ec", "Isabelline"));
        getColors().add(new Color("#f56991", "Light Crimson"));
        getColors().add(new Color("#f5deb3", "Wheat"));
        getColors().add(new Color("#f5f5dc", "Beige"));
        getColors().add(new Color("#f5f5f5", "White smoke"));
        getColors().add(new Color("#f5fffa", "Mint cream"));
        getColors().add(new Color("#f64a8a", "French rose"));
        getColors().add(new Color("#f6adc6", "Nadeshiko pink"));
        getColors().add(new Color("#f75394", "Violet Red"));
        getColors().add(new Color("#f77fbe", "Persian pink"));
        getColors().add(new Color("#f78fa7", "Pink Sherbet"));
        getColors().add(new Color("#f7e98e", "Flavescent"));
        getColors().add(new Color("#f88379", "Coral pink"));
        getColors().add(new Color("#f8d568", "Orange Yellow"));
        getColors().add(new Color("#f8de7e", "Jasmine"));
        getColors().add(new Color("#f8f4ff", "Magnolia"));
        getColors().add(new Color("#f8f8ff", "Ghost white"));
        getColors().add(new Color("#f9429e", "Rose bonbon"));
        getColors().add(new Color("#f94d00", "Tangelo"));
        getColors().add(new Color("#f984e5", "Pale magenta"));
        getColors().add(new Color("#f984ef", "Light fuchsia pink"));
        getColors().add(new Color("#fad6a5", "Champagne"));
        getColors().add(new Color("#fad6a5", "Deep champagne"));
        getColors().add(new Color("#fad6a5", "Sunset"));
        getColors().add(new Color("#fada5e", "Jonquil"));
        getColors().add(new Color("#fada5e", "Naples yellow"));
        getColors().add(new Color("#fada5e", "Stil de grain yellow"));
        getColors().add(new Color("#fadadd", "Pale pink"));
        getColors().add(new Color("#fadfad", "Peach yellow"));
        getColors().add(new Color("#fae7b5", "Banana Mania"));
        getColors().add(new Color("#faebd7", "Antique white"));
        getColors().add(new Color("#faebd7", "Moccasin"));
        getColors().add(new Color("#faf0be", "Blond"));
        getColors().add(new Color("#faf0e6", "Linen"));
        getColors().add(new Color("#fafad2", "Light goldenrod yellow"));
        getColors().add(new Color("#fb607f", "Brink pink"));
        getColors().add(new Color("#fba0e3", "Lavender rose"));
        getColors().add(new Color("#fbaed2", "Lavender pink"));
        getColors().add(new Color("#fbcce7", "Classic rose"));
        getColors().add(new Color("#fbceb1", "Apricot"));
        getColors().add(new Color("#fbec5d", "Corn"));
        getColors().add(new Color("#fbec5d", "Maize"));
        getColors().add(new Color("#fc0fc0", "Shocking pink"));
        getColors().add(new Color("#fc6c85", "Wild Watermelon"));
        getColors().add(new Color("#fc74fd", "Pink Flamingo"));
        getColors().add(new Color("#fc89ac", "Tickle Me Pink"));
        getColors().add(new Color("#fc8eac", "Flamingo pink"));
        getColors().add(new Color("#fcc200", "Golden poppy"));
        getColors().add(new Color("#fcf75e", "Icterine"));
        getColors().add(new Color("#fd0e35", "Tractor red"));
        getColors().add(new Color("#fd5e53", "Sunset Orange"));
        getColors().add(new Color("#fdbcb4", "Melon"));
        getColors().add(new Color("#fdd5b1", "Light apricot"));
        getColors().add(new Color("#fddde6", "Piggy pink"));
        getColors().add(new Color("#fdee00", "Aureolin"));
        getColors().add(new Color("#fdf5e6", "Old lace"));
        getColors().add(new Color("#fdfd96", "Pastel yellow"));
        getColors().add(new Color("#fe28a2", "Persian rose"));
        getColors().add(new Color("#fe4eda", "Purple pizzazz"));
        getColors().add(new Color("#fe59c2", "Neon fuchsia"));
        getColors().add(new Color("#fe6f5e", "Bittersweet"));
        getColors().add(new Color("#fefe22", "Laser Lemon"));
        getColors().add(new Color("#ff0000", "Red"));
        getColors().add(new Color("#ff0028", "Ruddy"));
        getColors().add(new Color("#ff0038", "Carmine red"));
        getColors().add(new Color("#ff003f", "Electric crimson"));
        getColors().add(new Color("#ff0040", "Carmine"));
        getColors().add(new Color("#ff004f", "Folly"));
        getColors().add(new Color("#ff007f", "Bright pink"));
        getColors().add(new Color("#ff007f", "Rose"));
        getColors().add(new Color("#ff00ff", "Famous"));
        getColors().add(new Color("#ff00ff", "Fuchsia"));
        getColors().add(new Color("#ff00ff", "Magenta"));
        getColors().add(new Color("#ff033e", "American rose"));
        getColors().add(new Color("#ff0800", "Candy apple red"));
        getColors().add(new Color("#ff1493", "Deep pink"));
        getColors().add(new Color("#ff1493", "Fluorescent pink"));
        getColors().add(new Color("#ff1dce", "Hot magenta"));
        getColors().add(new Color("#ff2052", "Awesome"));
        getColors().add(new Color("#ff2400", "Scarlet"));
        getColors().add(new Color("#ff2800", "Ferrari Red"));
        getColors().add(new Color("#ff33cc", "Razzle dazzle rose"));
        getColors().add(new Color("#ff355e", "Radical Red"));
        getColors().add(new Color("#ff3800", "Coquelicot"));
        getColors().add(new Color("#ff4040", "Coral red"));
        getColors().add(new Color("#ff43a4", "Wild Strawberry"));
        getColors().add(new Color("#ff4500", "Orange red"));
        getColors().add(new Color("#ff4f00", "International orange"));
        getColors().add(new Color("#ff5349", "Red Orange"));
        getColors().add(new Color("#ff55a3", "Brilliant rose"));
        getColors().add(new Color("#ff5a36", "Portland Orange"));
        getColors().add(new Color("#ff6347", "Tomato"));
        getColors().add(new Color("#ff66cc", "Rose pink"));
        getColors().add(new Color("#ff6700", "Safety orange"));
        getColors().add(new Color("#ff6961", "Pastel red"));
        getColors().add(new Color("#ff69b4", "Hot pink"));
        getColors().add(new Color("#ff6e4a", "Outrageous Orange"));
        getColors().add(new Color("#ff6fff", "Ultra pink"));
        getColors().add(new Color("#ff7518", "Pumpkin"));
        getColors().add(new Color("#ff77ff", "Fuchsia pink"));
        getColors().add(new Color("#ff7f50", "Coral"));
        getColors().add(new Color("#ff8243", "Mango Tango"));
        getColors().add(new Color("#ff8c00", "Dark orange"));
        getColors().add(new Color("#ff8c69", "Salmon"));
        getColors().add(new Color("#ff8f00", "Princeton orange"));
        getColors().add(new Color("#ff91a4", "Salmon pink"));
        getColors().add(new Color("#ff9933", "Deep saffron"));
        getColors().add(new Color("#ff9966", "Atomic tangerine"));
        getColors().add(new Color("#ff9999", "Light salmon pink"));
        getColors().add(new Color("#ff9f00", "Orange peel"));
        getColors().add(new Color("#ffa07a", "Light salmon"));
        getColors().add(new Color("#ffa089", "Vivid tangerine"));
        getColors().add(new Color("#ffa343", "Neon Carrot"));
        getColors().add(new Color("#ffa500", "Orange"));
        getColors().add(new Color("#ffa6c9", "Carnation pink"));
        getColors().add(new Color("#ffa700", "Chrome yellow"));
        getColors().add(new Color("#ffa812", "Dark tangerine"));
        getColors().add(new Color("#ffae42", "Yellow Orange"));
        getColors().add(new Color("#ffb300", "UCLA Gold"));
        getColors().add(new Color("#ffb347", "Pastel orange"));
        getColors().add(new Color("#ffb6c1", "Light pink"));
        getColors().add(new Color("#ffb7c5", "Cherry blossom pink"));
        getColors().add(new Color("#ffba00", "Selective yellow"));
        getColors().add(new Color("#ffbcd9", "Cotton candy"));
        getColors().add(new Color("#ffbd88", "Macaroni and Cheese"));
        getColors().add(new Color("#ffbf00", "Amber"));
        getColors().add(new Color("#ffbf00", "Fluorescent orange"));
        getColors().add(new Color("#ffc0cb", "Pink"));
        getColors().add(new Color("#ffc1cc", "Bubble gum"));
        getColors().add(new Color("#ffc40c", "Mikado yellow"));
        getColors().add(new Color("#ffc87c", "Topaz"));
        getColors().add(new Color("#ffcba4", "Deep peach"));
        getColors().add(new Color("#ffcc00", "Tangerine yellow"));
        getColors().add(new Color("#ffcc00", "USC Gold"));
        getColors().add(new Color("#ffcc33", "Sunglow"));
        getColors().add(new Color("#ffd1dc", "Pastel pink"));
        getColors().add(new Color("#ffd700", "Gold"));
        getColors().add(new Color("#ffd800", "School bus yellow"));
        getColors().add(new Color("#ffdab9", "Peach puff"));
        getColors().add(new Color("#ffdb58", "Mustard"));
        getColors().add(new Color("#ffdead", "Navajo white"));
        getColors().add(new Color("#ffdf00", "Golden yellow"));
        getColors().add(new Color("#ffe135", "Banana yellow"));
        getColors().add(new Color("#ffe4c4", "Bisque"));
        getColors().add(new Color("#ffe4e1", "Misty rose"));
        getColors().add(new Color("#ffe5b4", "Peach"));
        getColors().add(new Color("#ffebcd", "Blanched Almond"));
        getColors().add(new Color("#ffef00", "Canary yellow"));
        getColors().add(new Color("#ffefd5", "Papaya whip"));
        getColors().add(new Color("#fff0f5", "Lavender blush"));
        getColors().add(new Color("#fff44f", "Lemon Yellow"));
        getColors().add(new Color("#fff5ee", "Seashell"));
        getColors().add(new Color("#fff600", "Cadmium yellow"));
        getColors().add(new Color("#fff700", "Lemon"));
        getColors().add(new Color("#fff8dc", "Cornsilk"));
        getColors().add(new Color("#fff8e7", "Cosmic latte"));
        getColors().add(new Color("#fffacd", "Lemon chiffon"));
        getColors().add(new Color("#fffaf0", "Floral white"));
        getColors().add(new Color("#fffafa", "Snow"));
        getColors().add(new Color("#fffdd0", "Cream"));
        getColors().add(new Color("#ffff00", "Electric yellow"));
        getColors().add(new Color("#ffff00", "Yellow"));
        getColors().add(new Color("#ffff31", "Daffodil"));
        getColors().add(new Color("#ffff66", "Unmellow Yellow"));
        getColors().add(new Color("#ffff99", "Canary"));
        getColors().add(new Color("#ffffed", "Light yellow"));
        getColors().add(new Color("#fffff0", "Ivory"));
        getColors().add(new Color("#ffffff", "White"));

        //Collections.reverse(getColors());
    }
}
